general:
  dbname: udd
  dbport: 5441
  types:
    sources: module udd.sources_gatherer
    packages: module udd.packages_gatherer
    setup: exec python db_manager.py
    delete: exec python db_manager.py
    src-pkg: module udd.src_and_pkg_gatherer
    popcon: module udd.popcon_gatherer
    testing-migrations: module udd.testing_migrations_gatherer
    upload-history: module udd.upload_history_gatherer
    orphaned-packages: module udd.orphaned_packages_gatherer
    bugs: exec DEBBUGS_CONFIG_FILE=/org/udd.debian.org/bugs/bugs.debian.org/etc/config perl /org/udd.debian.org/udd/udd/bugs_gatherer.pl 
    carnivore: module udd.carnivore_gatherer
    lintian: module udd.lintian_gatherer
    debtags: module udd.debtags_gatherer
    ubuntu-bugs: module udd.ubuntu_bugs_gatherer
    ddtp: module udd.ddtp_gatherer
    ftpnew: module udd.ftpnew_gatherer
    screenshots: module udd.screenshot_gatherer
    dehs: module udd.dehs_gatherer
    ldap: module udd.ldap_gatherer
    wannabuild: module udd.wannabuild_gatherer
    removals: module udd.removals_gatherer
  timestamp-dir: /org/udd.debian.org/timestamps
  lock-dir: /org/udd.debian.org/locks
  archs:
   [alpha, amd64, arm, armeb, armel, hppa, hurd-i386,
    i386, i486, ia64, kfreebsd-amd64, kfreebsd-i386, mips,
    mipsel, powerpc, ppc64, s390, sparc, all, any, lpia, m32r, s390x, sh3,
    sh3eb, sh4, sh4eb, sh, knetbsd-i386, netbsd-alpha, sparc64,
    netbsd-i386, hurd-powerpc, kfreebsd-powerpc, netbsd-powerpc, hurd-sparc,
    kfreebsd-sparc, netbsd-sparc, darwin-i386, freebsd-i386, openbsd-i386, darwin-powerpc]

debian-etch:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/etch/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: etch

debian-etch-proposed-updates:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/etch-proposed-updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: etch-proposed-updates

debian-backports-etch:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/backports.org/ftp/dists/etch-backports/
  components: [main, contrib, non-free]
  distribution: debian-backports
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: etch

debian-volatile-etch:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/volatile.debian.org/archive/dists/etch/volatile/
  components: [main, contrib, non-free]
  distribution: etch-volatile
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: etch

debian-etch-security:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/security.debian.org/ftp/dists/etch/updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: etch-security

debian-lenny:
  type: src-pkg
  archs: [alpha, amd64, arm, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/lenny/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: lenny

debian-lenny-security:
  type: src-pkg
  archs: [alpha, amd64, arm, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/security.debian.org/ftp/dists/lenny/updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: lenny-security

debian-lenny-proposed-updates:
  type: src-pkg
  archs: [alpha, amd64, arm, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/lenny-proposed-updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: lenny-proposed-updates

debian-backports-lenny:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/backports.org/ftp/dists/lenny-backports/
  components: [main, contrib, non-free]
  distribution: debian-backports
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: lenny

debian-volatile-lenny:
  type: src-pkg
  archs: [alpha, amd64, arm, hppa, i386, ia64,  mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/volatile.debian.org/archive/dists/lenny/volatile/
  components: [main, contrib, non-free]
  distribution: lenny-volatile
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: lenny

debian-squeeze:
  type: src-pkg
  archs: [amd64, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/squeeze/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: squeeze

debian-squeeze-security:
  type: src-pkg
  archs: [amd64, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/security.debian.org/ftp/dists/squeeze/updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: squeeze-security

debian-squeeze-proposed-updates:
  type: src-pkg
  archs: [amd64, armel, hppa,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/squeeze-proposed-updates/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: squeeze-proposed-updates

debian-sid:
  type: src-pkg
  archs: [alpha, amd64, armel, hppa, hurd-i386,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/sid/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: sid

debian-experimental:
  type: src-pkg
  archs: [alpha, amd64, armel, hppa, hurd-i386,
          i386, ia64, mips,
          mipsel, powerpc, s390, sparc]       
  directory: /org/mirrors/ftp.debian.org/ftp/dists/experimental/
  components: [main, contrib, non-free]
  distribution: debian
  packages-table: packages
  sources-table: sources
  uploaders-table: uploaders
  packages-schema: packages
  sources-schema: sources
  release: experimental

ubuntu-lucid:
  type: src-pkg
  archs: [amd64, i386]
  directory: /org/mirrors/ubuntu.com/ftp/dists/lucid/
  components: [main, multiverse, universe, restricted]
  distribution: ubuntu
  release: lucid
  packages-table: ubuntu_packages
  sources-table: ubuntu_sources
  uploaders-table: ubuntu_uploaders
  packages-schema: packages
  sources-schema: sources

ubuntu-karmic:
  type: src-pkg
  archs: [amd64, i386]
  directory: /org/mirrors/ubuntu.com/ftp/dists/karmic/
  components: [main, multiverse, universe, restricted]
  distribution: ubuntu
  release: karmic
  packages-table: ubuntu_packages
  sources-table: ubuntu_sources
  uploaders-table: ubuntu_uploaders
  packages-schema: packages
  sources-schema: sources

ubuntu-jaunty:
  type: src-pkg
  archs: [amd64, i386]
  directory: /org/mirrors/ubuntu.com/ftp/dists/jaunty/
  components: [main, multiverse, universe, restricted]
  distribution: ubuntu
  release: jaunty
  packages-table: ubuntu_packages
  sources-table: ubuntu_sources
  uploaders-table: ubuntu_uploaders
  packages-schema: packages
  sources-schema: sources

ubuntu-intrepid:
  type: src-pkg
  archs: [amd64, i386]
  directory: /org/mirrors/ubuntu.com/ftp/dists/intrepid/
  components: [main, multiverse, universe, restricted]
  distribution: ubuntu
  release: intrepid
  packages-table: ubuntu_packages
  sources-table: ubuntu_sources
  uploaders-table: ubuntu_uploaders
  packages-schema: packages
  sources-schema: sources

ubuntu-hardy:
  type: src-pkg
  archs: [amd64, i386]
  directory: /org/mirrors/ubuntu.com/ftp/dists/hardy/
  components: [main, multiverse, universe, restricted]
  distribution: ubuntu
  release: hardy
  packages-table: ubuntu_packages
  sources-table: ubuntu_sources
  uploaders-table: ubuntu_uploaders
  packages-schema: packages
  sources-schema: sources

debian-popcon:
  type: popcon
  path: /org/udd.debian.org/tmp/all-popcon-results.txt.gz
  update-command: wget -q -O /org/udd.debian.org/tmp/all-popcon-results.txt.gz http://popcon.debian.org/all-popcon-results.txt.gz
  table: popcon
  schema: popcon
  packages-table: packages
  
ubuntu-popcon:
  type: popcon
  path: /org/udd.debian.org/tmp/ubuntu-popcon-results.txt.gz
  update-command: wget -q -O /org/udd.debian.org/tmp/ubuntu-popcon-results.txt.gz http://popcon.ubuntu.com/all-popcon-results.txt.gz
  table: ubuntu_popcon
  schema: popcon
  packages-table: ubuntu_packages

testing-migrations:
  type: testing-migrations
  path: /org/udd.debian.org/testing-status/testing-status.raw
  update-command: /org/udd.debian.org/udd/scripts/testing-status-update
  schema: testing_migrations
  table: migrations

upload-history:
  type: upload-history
  path: /org/udd.debian.org/tmp/upload-history
  update-command: if [ ! -e /org/udd.debian.org/tmp/upload-history/ ]; then mkdir /org/udd.debian.org/tmp/upload-history/; fi; rm -rf /org/udd.debian.org/tmp/upload-history/*; wget -q -r --no-parent -nd -A debian-devel-* -P /org/udd.debian.org/tmp/upload-history http://qa.debian.org/~filippo/ddc/
  schema: upload_history
  table: upload_history

bugs:
  type: bugs
  archived: false
  table: bugs
  schema: bugs
  archived-table: archived_bugs
  packages-table: packages
  usertags-table: bugs_usertags
  sources-table: sources
  update-command: cd /org/udd.debian.org/bugs ; ./bugsync

bugs-archive:
  type: bugs
  archived: true
  table: bugs
  schema: bugs
  archived-table: archived_bugs
  packages-table: packages
  usertags-table: bugs_usertags
  sources-table: sources
  update-command: cd /org/udd.debian.org/bugs ; ./bugsync

orphaned-packages:
  type: orphaned-packages
  table: orphaned_packages
  setup: orphaned_packages
  unarchived-table: bugs
  schema: orphaned_packages
  bugs-path: /org/bugs.debian.org

carnivore:
  type: carnivore
  update-command: /org/udd.debian.org/udd/scripts/sync-carnivore.sh
  path: /org/udd.debian.org/mirrors/qa.debian.org/carnivore/report
  emails-table: carnivore_emails
  names-table: carnivore_names
  keys-table: carnivore_keys
  login-table: carnivore_login
  schema: carnivore

lintian:
  type: lintian
  update-command: rm -f /org/udd.debian.org/mirrors/lintian.log && wget -q http://lintian.debian.org/lintian.log -O /org/udd.debian.org/mirrors/lintian.log
  path: /org/udd.debian.org/mirrors/lintian.log
  table: lintian
  schema: lintian

dehs:
  type: dehs
  update-command: rm -f /org/udd.debian.org/mirrors/dehs.txt && wget -q http://dehs.alioth.debian.org/udd_dump.txt  -O /org/udd.debian.org/mirrors/dehs.txt
  path: /org/udd.debian.org/mirrors/dehs.txt

ldap:
  type: ldap

debtags:
  type: debtags
  update-command: rm -f /org/udd.debian.org/mirrors/debtags.txt && wget -q http://svn.debian.org/viewsvn/*checkout*/debtags/tagdb/tags -O /org/udd.debian.org/mirrors/debtags.txt
  path: /org/udd.debian.org/mirrors/debtags.txt
  table: debtags
  schema: debtags

ubuntu-bugs:
   type: ubuntu-bugs

ddtp:
   type: ddtp
   update-command: /org/udd.debian.org/udd/scripts/fetch_ddtp_translations.sh /org/udd.debian.org/mirrors/ddtp ddtp.debian.net/Translation_udd sid lenny squeeze
   path: /org/udd.debian.org/mirrors/ddtp
   mirror: ddtp.debian.net/Translation_udd
   files: Translation-.*\.gz
   releases: sid lenny squeeze
   table: ddtp
   schema: ddtp

ftpnew:
  type: ftpnew
  update-command: /org/udd.debian.org/udd/scripts/fetch_ftpnew.sh
  path: /org/udd.debian.org/mirrors/ftpnew
  cache: /org/udd.debian.org/mirrors/cache
  ftpmasterURL: http://ftp-master.debian.org/new/
  table_sources:  new_sources
  table_packages: new_packages
  releases_ignore: "'etch'"

screenshots:
  type: screenshots
  update-command: /org/udd.debian.org/udd/scripts/fetch_screenshots.sh
  path: /org/udd.debian.org/mirrors/screenshots
  cache: /org/udd.debian.org/mirrors/cache
  table:  screenshots
  screenshots_json: /org/udd.debian.org/mirrors/screenshots/screenshots.json

wannabuild:
  type: wannabuild
  wbdb: "dbname=wanna-build host=localhost port=5433 user=guest"
  archs: [alpha, amd64, arm, armel, hppa, hurd-i386,
    i386, ia64, kfreebsd-amd64, kfreebsd-i386, mips,
    mipsel, powerpc, s390, sparc]

removals:
  type: removals
  update-command: wget -q http://ftp-master.debian.org/removals-full.txt -O - | scripts/fix-removal-timestamps.py > /org/udd.debian.org/mirrors/removals-full.txt
  path: /org/udd.debian.org/mirrors/removals-full.txt
  table: package_removal
  schema: package_removal
