general:
  dbname: udd
  dbport: 5452
  types:
    blends-metadata: module udd.blends_metadata_gatherer
  timestamp-dir: /srv/udd.debian.org/timestamps
  lock-dir: /srv/udd.debian.org/locks
  archs:
   [alpha, amd64, arm, armeb, armel, armhf, hppa, hurd-i386,
    i386, i486, ia64, kfreebsd-amd64, kfreebsd-i386, mips,
    mipsel, powerpc, ppc64, s390, s390x, sparc, all, any, lpia, m32r, s390x, sh3,
    sh3eb, sh4, sh4eb, sh, knetbsd-i386, netbsd-alpha, sparc64,
    netbsd-i386, hurd-powerpc, kfreebsd-powerpc, netbsd-powerpc, hurd-sparc,
    kfreebsd-sparc, netbsd-sparc, darwin-i386, freebsd-i386, openbsd-i386, darwin-powerpc]

blends-metadata:
  type: blends-metadata
  update-command: /srv/udd.debian.org/udd/scripts/fetch_blends_metadata.sh
  path: /srv/udd.debian.org/mirrors/blends
  table-metadata: blends_metadata
  table-tasks: blends_tasks
  table-dependencies: blends_dependencies

