general:
  dbname: udd
  types:
    ftpnew: module udd.ftpnew_gatherer
  debug: 1
  lock-dir: /org/udd.debian.net/locks

  archs:
   [i386]

ftpnew:
  type: ftpnew
  update-command: /org/udd.debian.net/udd/scripts/fetch_ftpnew.sh
  path: /org/udd.debian.net/mirrors/ftpnew
  cache: /org/udd.debian.net/mirrors/cache
  ftpmasterURL: http://ftp-master.debian.org/new/
  table_sources:  new_sources
  table_packages: new_packages
  releases_ignore: "'etch'"
