#!/bin/sh

set -e
cd /srv/udd.debian.org/udd/web/dumps/
umask 022
# exclude dumps from backups, at DSA's request (ivodd 20140101)
touch .nobackup

pg_dump --no-owner -p 5452 -Fc -T ldap -T really_active_dds -T pts -f udd.dump.new udd
mv udd.dump.new udd.dump
