#!/bin/bash

set -e

mkdir -p /srv/udd.debian.org/tmp/hints
cd /srv/udd.debian.org/tmp/hints
rm * || true
wget -q -r -np -nH -nd -nc http://release.debian.org/britney/hints/
rm index.html README robots.txt
